env: "CartPole-v1"
gamma: 0.999
lambda: 0.95
timesteps_per_rollout: 256
epochs_per_rollout: 3
minibatches_per_rollout: 8
entropy_bonus: 0.01
clip_range: 0.2
reward_norm: true
lr: 5e-4
workers: 1
env_per_worker: 64
total_timesteps: 25e6