env: "procgen:procgen-coinrun-v0"
gamma: 0.99
lam: 0.95
timesteps_per_rollout: 256
epochs_per_rollout: 3
minibatches_per_rollout: 8
entropy_bonus: 0.01
epsilon: 0.2
reward_norm: true
lr: 2.5e-4
workers: 1
env_per_worker: 64
total_timesteps: 30000 # 25e6